### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by dicook** [Sayani07/ProViz_TimeGrans#1]
--- FIXED ----
processing file: thesis_proviz.Rmd
Error in parse_block(g[-1], g[1], params.src) : 
  duplicate label 'wday-wknd'
Calls: <Anonymous> ... process_file -> split_file -> lapply -> FUN -> parse_block
Execution halted
---------------

----- NEED YOU TO FIX----
Quitting from lines 542-567 (thesis_proviz.Rmd) 
Error in gzfile(file, "rb") : cannot open the connection
Calls: <Anonymous> ... withVisible -> eval -> eval -> read_rds -> readRDS -> gzfile
Execution halted

You have a hard-coded directory reference: 

Data_Halls_Residence <-read_rds("~/Documents//MRS_Consumption/DHResidence.rds")

**Comment by Sayani07** [comment]
Fixed now.
